### ISSUE TITLE
HT Ratio variable problem

### ISSUE THREAD

**Issue by andresc27** [andresc27/FourTopsCMSOpenData#4]
The variable  $H_{ratio}^T$ of the $H_T$ of the four highest- $p_T$ jets in the event in the single-electron.
Comprobar el plot obtenido en el Notebook [Electron Plots](https://github.com/andresc27/FourTopsCMSOpenData/blob/4cc27171f42cd36651faab90c9914e2f522df111/Notebooks/Electron_plot.ipynb#L466)  con los plots de la Nota de analisis apendice A pagina 26.

El codigo para esta variable se puede ver en este [Notebook](https://github.com/andresc27/FourTopsCMSOpenData/blob/4cc27171f42cd36651faab90c9914e2f522df111/Notebooks/Electron_Analyzer.ipynb#L351)

La receta que muestra la publicacion es:
The ratio ($H_{ratio}^T$) of the $H_T$ of the four highest- $p_T$ jets in the event in the single-lepton, to the $H_T$ of the other jets in the event

Sin embargo, @caredg, no estoy seguro de haberlo hecho bien, ya que en primer lugar no he podido saber si H_T es la suma escalar del pt de todas las particular (jets, bjets, electrones) o solo es la suma del pt de los jets. Luego, no se si el H_T que pide la variable es la suma de todo el pt del evento o la suma del pt restante una vez sumados los 4 valores mas altos. 

Espero haberme hecho entender :)

**Comment by caredg** [comment]
@andresc27 La descripción que mencionas dice claramente que "...of the $H_T$ of the four highest- $p_T$ jets in the event in the single-lepton, to the $H_T$ of the other jets in the event".  Es decir que no es de todas las partículas si no sólo de los jets.  Lo que es más interesante es que pienses en la razón para esto.  Dibuja los diagramas de Feynman de `ttbar` y `tttt` y mira los decaimientos (recuerda, sólo un W decae leptónicamente) y justifica esa variable físicamente.  Cuando esto tenga sentido en tu cabeza (y me lo puedas explicar), se te hará más fácil reparar cualquier cosa en el código respecto a esta variable.

**Comment by andresc27** [comment]
@caredg sí, lo de la suma de los 4 jets con pt más alto sí lo entiendo. Pero me refería también a que, si el H_T sería la suma del pt de los jets restantes o de todos los jets del evento.
Por ejemplo, si tengo: jets=[[,1,2,3,4],[5,6,7,8,9]]
Entonces el H_T sería : 
H_T=[10, 25] que sería la suma de todos los valores de pt en cada evento
o
H_T=[0, 5] que solo es la suma de los pt restantes sin tomar en cuenta los 4 más altos.

En una referencia encontré que el H_T es la suma del pt de todos los jets en el evento, pero en otra encontré que el H_T es el pt remanente (o sea sin tomar en cuenta los 4 jets con valor más alto)

Ahora ya voy a corregir la variable y a hacer la tarea de los diagramas de Feynman. Gracias Edgar :)

**Comment by caredg** [comment]
Dice " $H_{T}$ of the other jets in the event", entonces yo entiendo que es de los jets restantes.... Te puedes convencer de que eso tendría sentido si haces el ejercicio de dibujar los diagramas

**Comment by andresc27** [comment]
@caredg Si también le puedes echar un vistazo a los histogramas de número de jets $N_j$, $H_T$ y $H_T^b$ por favor, son las variables que tengo por el momento. Me quedo atento a las observaciones que puedas hacerme sobre ello. :)

**Comment by caredg** [comment]
@andresc27 podrías colocar los gráficos aquí con las preocupaciones y comentarios respectivos?

**Comment by andresc27** [comment]
No se pueden subir imágenes al comentario. Quizá es buena idea hacer un documento de word compartido. 
Solo quería que pudieses revisar mis plots y que me des el visto bueno, yo considero que los plos de número de jets $N_j$, suma de pt de jets $H_T$ y suma de pt de bjets $H_T^b$ están bien (al compararlos con el paper original). 
Aunque el de número de jets se muestra algo más diferente al compararlo con los plots del análisis original.

Por otro lado, también quería preguntarte, luego de que corrija la variable $H_T^{ratio}$, serían suficientes variables ?
O, crees que puede ser útil construir alguna de estas dos variables (o ambas) ?

- The pT of the selected lepton $p_t^{l_1}$
- Third-highest CSV.

Por otro lado, una vez construidas las variables, qué más debería hacer ?  ( considerando que actualmente contaría con poco más de un mes para terminar el trabajo práctico )

Otra cosa, también podrías ayudarme revisando la parte escrita ? De igual manera, no sé si es mejor que te vaya compartiendo en .pdf los avances que haga o quizá es mejor compartirte el link de overleaf ?

Házmelo saber por favor.

**Comment by caredg** [comment]
Si se puede: [mira](https://github.com/pablobuitron/masterthesis/issues/9#issuecomment-1571413942)

**Comment by andresc27** [comment]
@caredg de la última reunión que tuvimos corregí la luminosidad, que ahora es de aproximadamente $2.3fb^{-1}$, obtuve los siguientes plots:
- pt de electrones 
![electrones](../blob/main/Notebooks/electronpt.png?raw=true)
- Número de jets
![jets](../blob/main/Notebooks/JetsNumber.png?raw=true)
- $H_T$ que es la suma del pt de todos los jets
![HT](../blob/main/Notebooks/HT.png?raw=true)
- $H_T^{b}$ que es la suma del pt de todos los bjets
![HTb](../blob/main/Notebooks/HTb.png?raw=true)
Hasta aquí, los plots se ven bien. Salvo que aun no me queda claro cómo usar "rebinFactor" que es un valor que se encuentra en cada plot.

-Ahora, con la variable $H_T^{ratio}$ 
![HTRatio](../blob/main/Notebooks/HTRatio.png?raw=true)
Con esta última variable, tomando en cuenta la tarea de dibujar los diagramas de Feynman. Tengo lo siguiente:
![pairtops](../blob/main/Notebooks/PairTops.jpeg?raw=true)
![4tops](../blob/main/Notebooks/4Tops.jpeg?raw=true)

Entiendo la razón de necesitar al menos 6 jets en $t\bar{t}t\bar{t}$  (que se obtienen del decaimiento de los respectivos quarks q). De igual manera, se obtienen 4bjets en la producción $t\bar{t}t\bar{t}$ y 2bjets en $t\bar{t}$ (que se obtiene del quark b). 

En este sentido, si tomamos la suma del pt mas alto de 4 jets, asumo que esta suma tomará en cuenta los jets de $t\bar{t}t\bar{t}$ ya que es el proceso más energético que $t\bar{t}$. En este caso, si a esta suma de pt la divido para el $H_T$ (suma del pt de los jets restantes en el evento), no es seguro que en ese ratio obtenga valores entre 0 y 1(como en la nota de analisis) ya que la suma del pt restante no necesariamente supera a la suma de 4 jets con el pt más alto.

A menos que sea la suma del pt restante dividida para la suma del pt de los 4 jets. (Esto fue con lo que me quede y corresponde a la imagen de $H_T^{ratio}$ que se muestra arriba) . Es esto correcto?

**Comment by caredg** [comment]
correcto
